# Generated by Django 2.1.15 on 2020-01-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='cart/products/%Y/%m/%d'),
        ),
    ]
